name: Update

on:
  workflow_dispatch:
    inputs: {}

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run update
        run: |
          set -e
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "Workflow trigger"
          new_version=$(./update.py -o rust-nightly-sources.json)
          git add rust-nightly-sources.json
          if ! git diff-index --quiet HEAD -- rust-nightly-sources.json; then
            git commit -m "Update to $new_version"
            git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          fi